import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        'primary-container': '#d8e2ff',
        'secondary': '#504dcd',
        'on-surface': '#2c333d',
        'tertiary-container': '#ce6ffd',
        'error-container': '#fe8983',
        'on-error': '#fff7f6',
        'on-primary-fixed': '#003d85',
        'error-dim': '#4e0309',
        'surface-bright': '#f9f9fe',
        'tertiary-fixed-dim': '#bf62ee',
        'on-tertiary-container': '#2f0046',
        'outline': '#747b86',
        'on-primary-fixed-variant': '#0058bb',
        'surface-tint': '#005bc1',
        'on-secondary-fixed': '#2d27ad',
        'surface': '#f9f9fe',
        'inverse-primary': '#4b8eff',
        'surface-container': '#ebeef7',
        'surface-dim': '#d3dae9',
        'primary-dim': '#004faa',
        'on-error-container': '#752121',
        'surface-container-lowest': '#ffffff',
        'inverse-surface': '#0c0e12',
        'tertiary-dim': '#801eb0',
        'surface-container-high': '#e4e8f3',
        'on-surface-variant': '#595f6a',
        'on-background': '#2c333d',
        'secondary-dim': '#4340c1',
        'on-tertiary-fixed': '#000000',
        'on-tertiary': '#fff7fc',
        'on-primary': '#f7f7ff',
        'on-secondary-fixed-variant': '#4c49c9',
        'on-tertiary-fixed-variant': '#3f005b',
        'secondary-fixed': '#e2dfff',
        'primary': '#005bc1',
        'outline-variant': '#acb2bf',
        'inverse-on-surface': '#9c9da1',
        'primary-fixed-dim': '#c2d4ff',
        'on-primary-container': '#004ea8',
        'on-secondary': '#fbf7ff',
        'background': '#f9f9fe',
        'secondary-fixed-dim': '#d2d0ff',
        'surface-variant': '#dce3f0',
        'surface-container-highest': '#dce3f0',
        'secondary-container': '#e2dfff',
        'primary-fixed': '#d8e2ff',
        'error': '#9f403d',
        'tertiary-fixed': '#ce6ffd',
        'tertiary': '#8e2fbd',
        'on-secondary-container': '#423ebf',
        'surface-container-low': '#f2f3fa'
      },
      fontFamily: {
        'headline': ['Manrope', 'sans-serif'],
        'body': ['Inter', 'sans-serif'],
        'label': ['Inter', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.25rem',
        'lg': '0.5rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
    },
  },
  plugins: [require('@tailwindcss/forms'), require('@tailwindcss/container-queries')],
}
export default config
