export interface VoiceInfo {
  id: string
  name: string
  speakerId: string
  gender: 'male' | 'female' | 'neutral'
  age: 'child' | 'young' | 'middle' | 'senior'
  language: 'zh' | 'en' | 'jp' | 'es' | 'other'
  scene: 'narration' | 'conversation' | 'advertising' | 'storytelling' | 'roleplay' | 'education' | 'customerService' | 'audiobook' | 'dubbing' | 'general'
  modelSupport: ('doubao-text-to-speech/seed-tts-1.0-concurr' | 'doubao-text-to-speech/seed-tts-1.0' | 'doubao-text-to-speech/seed-tts-2.0')[]
}

// Seed TTS 2.0 voices
const tts2Voices: VoiceInfo[] = [
  {
    id: 'vivi-2',
    name: 'Vivi 2.0',
    speakerId: 'zh_female_vv_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'xiaohe-2',
    name: '小何 2.0',
    speakerId: 'zh_female_xiaohe_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'yunzhou-2',
    name: '云舟 2.0',
    speakerId: 'zh_male_m191_uranus_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'tian-2',
    name: '小天 2.0',
    speakerId: 'zh_male_taocheng_uranus_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'liufei-2',
    name: '刘飞 2.0',
    speakerId: 'zh_male_liufei_uranus_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'sophie-2',
    name: '魅力苏菲 2.0',
    speakerId: 'zh_male_sophie_uranus_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'qingxin-2',
    name: '清新女声 2.0',
    speakerId: 'zh_female_qingxinnvsheng_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'cancan-2',
    name: '知性灿灿 2.0',
    speakerId: 'zh_female_cancan_uranus_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'sajiao-2',
    name: '撒娇学妹 2.0',
    speakerId: 'zh_female_sajiaoxuemei_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'xiaoyuan-2',
    name: '甜美小源 2.0',
    speakerId: 'zh_female_tianmeixiaoyuan_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'taozi-2',
    name: '甜美桃子 2.0',
    speakerId: 'zh_female_tianmeitaozi_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'shuangkuai-2',
    name: '爽快思思 2.0',
    speakerId: 'zh_female_shuangkuaisisi_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'peiqi-2',
    name: '佩奇猪 2.0',
    speakerId: 'zh_female_peiqi_uranus_bigtts',
    gender: 'female',
    age: 'child',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'linjian-2',
    name: '邻家女孩 2.0',
    speakerId: 'zh_female_linjianvhai_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'zixin-2',
    name: '少年梓辛 2.0',
    speakerId: 'zh_male_shaonianzixin_uranus_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'sunwukong-2',
    name: '猴哥 2.0',
    speakerId: 'zh_male_sunwukong_uranus_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'tina-2',
    name: 'Tina老师 2.0',
    speakerId: 'zh_female_yingyujiaoxue_uranus_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'education',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'nuan-2',
    name: '暖阳女声 2.0',
    speakerId: 'zh_female_kefunvsheng_uranus_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'children-2',
    name: '儿童绘本 2.0',
    speakerId: 'zh_female_xiaoxue_uranus_bigtts',
    gender: 'female',
    age: 'child',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'dayi-2',
    name: '大壹 2.0',
    speakerId: 'zh_male_dayi_uranus_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'mizai-2',
    name: '黑猫侦探社咪仔 2.0',
    speakerId: 'zh_female_mizai_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'jitang-2',
    name: '鸡汤女 2.0',
    speakerId: 'zh_female_jitangnv_uranus_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'meilin-2',
    name: '魅力女友 2.0',
    speakerId: 'zh_female_meilinvyou_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'liuchang-2',
    name: '流畅女声 2.0',
    speakerId: 'zh_female_liuchangnv_uranus_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'yichen-2',
    name: '儒雅逸辰 2.0',
    speakerId: 'zh_male_ruyayichen_uranus_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'tim',
    name: 'Tim',
    speakerId: 'en_male_tim_uranus_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'dacey',
    name: 'Dacey',
    speakerId: 'en_female_dacey_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
  {
    id: 'stokie',
    name: 'Stokie',
    speakerId: 'en_female_stokie_uranus_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-2.0'],
  },
]

// Seed TTS 1.0 voices
const tts1Voices: VoiceInfo[] = [
  {
    id: 'lengkugege',
    name: '冷酷哥哥',
    speakerId: 'zh_male_lengkugege_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tianxinxiaomei',
    name: '甜心小美',
    speakerId: 'zh_female_tianxinxiaomei_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'gaolengyujie',
    name: '高冷御姐',
    speakerId: 'zh_female_gaolengyujie_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aojiaobazong',
    name: '傲娇霸总',
    speakerId: 'zh_male_aojiaobazong_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'guangzhoudege',
    name: '广州德哥',
    speakerId: 'zh_male_guangzhoudege_emo_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jingqiangkanye',
    name: '京腔侃爷',
    speakerId: 'zh_male_jingqiangkanye_emo_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'linjuayi',
    name: '邻居阿姨',
    speakerId: 'zh_female_linjuayi_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'senior',
    language: 'zh',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yourougongzi',
    name: '优柔公子',
    speakerId: 'zh_male_yourougongzi_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruyayichen',
    name: '儒雅男友',
    speakerId: 'zh_male_ruyayichen_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'junlangnanyou',
    name: '俊朗男友',
    speakerId: 'zh_male_junlangnanyou_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'beijingxiaoye',
    name: '北京小爷',
    speakerId: 'zh_male_beijingxiaoye_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'roumeinvyou',
    name: '柔美女友',
    speakerId: 'zh_female_roumeinvyou_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yangguangqingnian',
    name: '阳光青年',
    speakerId: 'zh_male_yangguangqingnian_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'meilinvyou',
    name: '魅力女友',
    speakerId: 'zh_female_meilinvyou_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shuangkuaisisi',
    name: '爽快思思',
    speakerId: 'zh_female_shuangkuaisisi_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'candice',
    name: 'Candice',
    speakerId: 'en_female_candice_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'serena',
    name: 'Serena',
    speakerId: 'en_female_skye_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'glen',
    name: 'Glen',
    speakerId: 'en_male_glen_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sylus',
    name: 'Sylus',
    speakerId: 'en_male_sylus_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'corey',
    name: 'Corey',
    speakerId: 'en_male_corey_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'nadia',
    name: 'Nadia',
    speakerId: 'en_female_nadia_tips_emo_v2_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shenyeboke',
    name: '深夜播客',
    speakerId: 'zh_male_shenyeboke_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tina-teacher',
    name: 'Tina老师',
    speakerId: 'zh_female_yingyujiaoyu_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'education',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenrounshen',
    name: '温柔女神',
    speakerId: 'ICL_zh_female_wenrounvshen_239eff5e8ffa_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'vivi',
    name: 'Vivi',
    speakerId: 'zh_female_vv_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qinqienvsheng',
    name: '亲切女声',
    speakerId: 'zh_female_qinqienvsheng_moon_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shenmi',
    name: '机灵小伙',
    speakerId: 'ICL_zh_male_shenmi_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wuxi',
    name: '元气甜妹',
    speakerId: 'ICL_zh_female_wuxi_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenyinvsheng',
    name: '知心姐姐',
    speakerId: 'ICL_zh_female_wenyinvsheng_v1_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingyiyuxuan',
    name: '阳光阿辰',
    speakerId: 'zh_male_qingyiyuxuan_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xudong',
    name: '快乐小东',
    speakerId: 'zh_male_xudong_conversation_wvae_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lengkugege-icl',
    name: '冷酷哥哥',
    speakerId: 'ICL_zh_male_lengkugege_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'feicui',
    name: '纯澈女生',
    speakerId: 'ICL_zh_female_feicui_v1_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yuxin',
    name: '初恋女友',
    speakerId: 'ICL_zh_female_yuxin_v1_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xnx',
    name: '贴心闺蜜',
    speakerId: 'ICL_zh_female_xnx_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yry',
    name: '温柔白月光',
    speakerId: 'ICL_zh_female_yry_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bv705',
    name: '炀炀',
    speakerId: 'ICL_zh_male_BV705_streaming_cs_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jason',
    name: '开朗学长',
    speakerId: 'en_male_jason_conversation_wvae_bigtts',
    gender: 'male',
    age: 'young',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sophie',
    name: '魅力苏菲',
    speakerId: 'zh_female_sophie_conversation_wvae_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yilin',
    name: '贴心妹妹',
    speakerId: 'ICL_zh_female_yilin_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tianmeitaozi',
    name: '甜美桃子',
    speakerId: 'zh_female_tianmeitaozi_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingxinnvsheng',
    name: '清新女声',
    speakerId: 'zh_female_qingxinnvsheng_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhixingnvsheng',
    name: '知性女声',
    speakerId: 'zh_female_zhixingnvsheng_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingshuangnanda',
    name: '清爽男大',
    speakerId: 'zh_male_qingshuangnanda_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'linjianvhai',
    name: '邻家女孩',
    speakerId: 'zh_female_linjianvhai_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yuanboxiaoshu',
    name: '渊博小叔',
    speakerId: 'zh_male_yuanboxiaoshu_moon_bigtts',
    gender: 'male',
    age: 'senior',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yangguangqingnian-moon',
    name: '阳光青年',
    speakerId: 'zh_male_yangguangqingnian_moon_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tianmeixiaoyuan',
    name: '甜美小源',
    speakerId: 'zh_female_tianmeixiaoyuan_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingchezizi',
    name: '清澈梓梓',
    speakerId: 'zh_female_qingchezizi_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jieshuoxiaoming',
    name: '解说小明',
    speakerId: 'zh_male_jieshuoxiaoming_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'kailangjiejie',
    name: '开朗姐姐',
    speakerId: 'zh_female_kailangjiejie_moon_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'linjiananhai',
    name: '邻家男孩',
    speakerId: 'zh_male_linjiananhai_moon_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tianmeiyueyue',
    name: '甜美悦悦',
    speakerId: 'zh_female_tianmeiyueyue_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xinlingjitang',
    name: '心灵鸡汤',
    speakerId: 'zh_female_xinlingjitang_moon_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhixingwenwan',
    name: '知性温婉',
    speakerId: 'ICL_zh_female_zhixingwenwan_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'nuanxintitie',
    name: '暖心体贴',
    speakerId: 'ICL_zh_male_nuanxintitie_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'kailangqingkuai',
    name: '开朗轻快',
    speakerId: 'ICL_zh_male_kailangqingkuai_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'huoposhuanglang',
    name: '活泼爽朗',
    speakerId: 'ICL_zh_male_huoposhuanglang_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shuaizhenxiaohuo',
    name: '率真小伙',
    speakerId: 'ICL_zh_male_shuaizhenxiaohuo_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenrouxiaoge',
    name: '温柔小哥',
    speakerId: 'zh_male_wenrouxiaoge_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'cancan-mars',
    name: '灿灿/Shiny',
    speakerId: 'zh_female_cancan_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shuangkuaisisi-moon',
    name: '爽快思思/Skye',
    speakerId: 'zh_female_shuangkuaisisi_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenruanahu',
    name: '温暖阿虎/Alvin',
    speakerId: 'zh_male_wennuanahu_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shaonianzixin-moon',
    name: '少年梓辛/Brayan',
    speakerId: 'zh_male_shaonianzixin_moon_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenrouwenya',
    name: '温柔文雅',
    speakerId: 'ICL_zh_female_wenrouwenya_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'hupunan',
    name: '沪普男',
    speakerId: 'zh_male_hupunan_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lubanqihao',
    name: '鲁班七号',
    speakerId: 'zh_male_lubanqihao_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yangmi',
    name: '林潇',
    speakerId: 'zh_female_yangmi_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'linzhiling',
    name: '玲玲姐姐',
    speakerId: 'zh_female_linzhiling_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jiyejizi2',
    name: '春日部姐姐',
    speakerId: 'zh_female_jiyejizi2_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tangseng',
    name: '唐僧',
    speakerId: 'zh_male_tangseng_mars_bigtts',
    gender: 'male',
    age: 'senior',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhuangzhou',
    name: '庄周',
    speakerId: 'zh_male_zhuangzhou_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhubajie',
    name: '猪八戒',
    speakerId: 'zh_male_zhubajie_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ganmaodianyin',
    name: '感冒电音姐姐',
    speakerId: 'zh_female_ganmaodianyin_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'naying',
    name: '直率英子',
    speakerId: 'zh_female_naying_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'leidian',
    name: '女雷神',
    speakerId: 'zh_female_leidian_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yueyunv',
    name: '粤语小溏',
    speakerId: 'zh_female_yueyunv_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yuzhouzixuan',
    name: '豫州子轩',
    speakerId: 'zh_male_yuzhouzixuan_moon_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'daimengchuanmei',
    name: '呆萌川妹',
    speakerId: 'zh_female_daimengchuanmei_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'guangxiyuanzhou',
    name: '广西远舟',
    speakerId: 'zh_male_guangxiyuanzhou_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhoujielun',
    name: '双节棍小哥',
    speakerId: 'zh_male_zhoujielun_emo_v2_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wanwanxiaohe',
    name: '湾湾小何',
    speakerId: 'zh_female_wanwanxiaohe_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wanqudashu',
    name: '湾区大叔',
    speakerId: 'zh_female_wanqudashu_moon_bigtts',
    gender: 'female',
    age: 'senior',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'guozhoudege',
    name: '广州德哥',
    speakerId: 'zh_male_guozhoudege_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'haoyuxiaoge',
    name: '浩宇小哥',
    speakerId: 'zh_male_haoyuxiaoge_moon_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'beijingxiaoye-moon',
    name: '北京小爷',
    speakerId: 'zh_male_beijingxiaoye_moon_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jingqiangkanye-moon',
    name: '京腔侃爷/Harmony',
    speakerId: 'zh_male_jingqiangkanye_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'meituojieer',
    name: '妹坨洁儿',
    speakerId: 'zh_female_meituojieer_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chunzhenshaonv',
    name: '纯真少女',
    speakerId: 'ICL_zh_female_chunzhenshaonv_e588402fb8ad_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xiaonaigou',
    name: '奶气小生',
    speakerId: 'ICL_zh_male_xiaonaigou_edf58cf28b8b_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jinglingxiangdao',
    name: '精灵向导',
    speakerId: 'ICL_zh_female_jinglingxiangdao_1beb294a9e3e_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'menyoupingxiaoge',
    name: '闷油瓶小哥',
    speakerId: 'ICL_zh_male_menyoupingxiaoge_ffed9fc2fee7_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'anrenqinzhu',
    name: '黯刃秦主',
    speakerId: 'ICL_zh_male_anrenqinzhu_cd62e63dcdab_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'badaozongcai',
    name: '霸道总裁',
    speakerId: 'ICL_zh_male_badaozongcai_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ganliv1',
    name: '妩媚可人',
    speakerId: 'ICL_zh_female_ganli_v1_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xiangliangya',
    name: '邪魅御姐',
    speakerId: 'ICL_zh_female_xiangliangya_v1_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xiaozhangms',
    name: '嚣张小哥',
    speakerId: 'ICL_zh_male_ms_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yuyouti',
    name: '油腻大叔',
    speakerId: 'ICL_zh_male_you_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'guaogongzi',
    name: '孤傲公子',
    speakerId: 'ICL_zh_male_guaogongzi_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'huzishu',
    name: '胡子叔叔',
    speakerId: 'ICL_zh_male_huzi_v1_tob',
    gender: 'male',
    age: 'senior',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'luoqingv1',
    name: '性感魅惑',
    speakerId: 'ICL_zh_female_luoqing_v1_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiao3',
    name: '病弱公子',
    speakerId: 'ICL_zh_male_bingruogongzi_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiao3nv',
    name: '邪魅女王',
    speakerId: 'ICL_zh_female_bingjiao3_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aomanqingnian',
    name: '傲慢青年',
    speakerId: 'ICL_zh_male_aomanqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'cujingnansheng',
    name: '醋精男生',
    speakerId: 'ICL_zh_male_cujingnansheng_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shuanglangshaonian',
    name: '爽朗少年',
    speakerId: 'ICL_zh_male_shuanglangshaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sajiaonanyou',
    name: '撒娇男友',
    speakerId: 'ICL_zh_male_sajiaonanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenrounanyou',
    name: '温柔男友',
    speakerId: 'ICL_zh_male_wenrounanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenshunshaonian',
    name: '温顺少年',
    speakerId: 'ICL_zh_male_wenshunshaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'naigounanyou',
    name: '粘人男友',
    speakerId: 'ICL_zh_male_naigounanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sajiaonansheng',
    name: '撒娇男生',
    speakerId: 'ICL_zh_male_sajiaonansheng_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'huoponanyou',
    name: '活泼男友',
    speakerId: 'ICL_zh_male_huoponanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tianxinanyou',
    name: '甜系男友',
    speakerId: 'ICL_zh_male_tianxinanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'huoliqingnian',
    name: '活力青年',
    speakerId: 'ICL_zh_male_huoliqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'kailangqingnian',
    name: '开朗青年',
    speakerId: 'ICL_zh_male_kailangqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lengmoxiongzhang',
    name: '冷漠兄长',
    speakerId: 'ICL_zh_male_lengmoxiongzhang_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tiancaitongzhuo',
    name: '天才同桌',
    speakerId: 'ICL_zh_male_tiancaitongzhuo_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'pianpiangongzi',
    name: '翩翩公子',
    speakerId: 'ICL_zh_male_pianpiangongzi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'mengdongqingnian',
    name: '懵懂青年',
    speakerId: 'ICL_zh_male_mengdongqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lenglianxiongzhang',
    name: '冷脸兄长',
    speakerId: 'ICL_zh_male_lenglianxiongzhang_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiaoshaonian',
    name: '病娇少年',
    speakerId: 'ICL_zh_male_bingjiaoshaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiaonanyou',
    name: '病娇男友',
    speakerId: 'ICL_zh_male_bingjiaonanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingruoshaonian',
    name: '病弱少年',
    speakerId: 'ICL_zh_male_bingruoshaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yiqishaonian',
    name: '意气少年',
    speakerId: 'ICL_zh_male_yiqishaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ganjingshaonian',
    name: '干净少年',
    speakerId: 'ICL_zh_male_ganjingshaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lengmonanyou',
    name: '冷漠男友',
    speakerId: 'ICL_zh_male_lengmonanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jingyingqingnian',
    name: '精英青年',
    speakerId: 'ICL_zh_male_jingyingqingnian_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'rexueshaonian',
    name: '热血少年',
    speakerId: 'ICL_zh_male_rexueshaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingshuangshaonian',
    name: '清爽少年',
    speakerId: 'ICL_zh_male_qingshuangshaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhongerqingnian',
    name: '中二青年',
    speakerId: 'ICL_zh_male_zhongerqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lingyunqingnian',
    name: '凌云青年',
    speakerId: 'ICL_zh_male_lingyunqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zifuqingnian',
    name: '自负青年',
    speakerId: 'ICL_zh_male_zifuqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bujiqingnian',
    name: '不羁青年',
    speakerId: 'ICL_zh_male_bujiqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruyajunzi',
    name: '儒雅君子',
    speakerId: 'ICL_zh_male_ruyajunzi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'diyinchenyu',
    name: '低音沉郁',
    speakerId: 'ICL_zh_male_diyinchenyu_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lenglianxueba',
    name: '冷脸学霸',
    speakerId: 'ICL_zh_male_lenglianxueba_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruyazongcai',
    name: '儒雅总裁',
    speakerId: 'ICL_zh_male_ruyazongcai_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shenchenzongcai',
    name: '深沉总裁',
    speakerId: 'ICL_zh_male_shenchenzongcai_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xiaohouye',
    name: '小侯爷',
    speakerId: 'ICL_zh_male_xiaohouye_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'gugaogongzi',
    name: '孤高公子',
    speakerId: 'ICL_zh_male_gugaogongzi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhangjianjunzi',
    name: '仗剑君子',
    speakerId: 'ICL_zh_male_zhangjianjunzi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenrunxuezhe',
    name: '温润学者',
    speakerId: 'ICL_zh_male_wenrunxuezhe_tob',
    gender: 'male',
    age: 'senior',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qinqieqingnian',
    name: '亲切青年',
    speakerId: 'ICL_zh_male_qinqieqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenrouxuezhang',
    name: '温柔学长',
    speakerId: 'ICL_zh_male_wenrouxuezhang_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'gaolengzongcai',
    name: '高冷总裁',
    speakerId: 'ICL_zh_male_gaolengzongcai_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lengjungaozhi',
    name: '冷峻高智',
    speakerId: 'ICL_zh_male_lengjungaozhi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chanruoshaoye',
    name: '孱弱少爷',
    speakerId: 'ICL_zh_male_chanruoshaoye_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zixinqingnian',
    name: '自信青年',
    speakerId: 'ICL_zh_male_zixinqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingseqingnian',
    name: '青涩青年',
    speakerId: 'ICL_zh_male_qingseqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xuebatongzhuo',
    name: '学霸同桌',
    speakerId: 'ICL_zh_male_xuebatongzhuo_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lengaozongcai',
    name: '冷傲总裁',
    speakerId: 'ICL_zh_male_lengaozongcai_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yuanqishaonian',
    name: '元气少年',
    speakerId: 'ICL_zh_male_yuanqishaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'satuoqingnian',
    name: '洒脱青年',
    speakerId: 'ICL_zh_male_satuoqingnian_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhishuaiqingnian',
    name: '直率青年',
    speakerId: 'ICL_zh_male_zhishuaiqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'siwenqingnian',
    name: '斯文青年',
    speakerId: 'ICL_zh_male_siwenqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'junyigongzi',
    name: '俊逸公子',
    speakerId: 'ICL_zh_male_junyigongzi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhangjianxiake',
    name: '仗剑侠客',
    speakerId: 'ICL_zh_male_zhangjianxiake_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jijiaozhineng',
    name: '机甲智能',
    speakerId: 'ICL_zh_male_jijiaozhineng_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'naiqimengwa',
    name: '奶气萌娃',
    speakerId: 'zh_male_naiqimengwa_mars_bigtts',
    gender: 'male',
    age: 'child',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'popo',
    name: '婆婆',
    speakerId: 'zh_female_popo_mars_bigtts',
    gender: 'female',
    age: 'senior',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'gaolengyujie',
    name: '高冷御姐',
    speakerId: 'zh_female_gaolengyujie_moon_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aojiaobazong-moon',
    name: '傲娇霸总',
    speakerId: 'zh_male_aojiaobazong_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'meilinvyou-moon',
    name: '魅力女友',
    speakerId: 'zh_female_meilinvyou_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shenyeboke-moon',
    name: '深夜播客',
    speakerId: 'zh_male_shenyeboke_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sajiaonvyou-moon',
    name: '撒娇学妹',
    speakerId: 'zh_female_yuanqinvyou_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingruoshaonv',
    name: '病弱少女',
    speakerId: 'ICL_zh_female_bingruoshaonv_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'huopovhai',
    name: '活泼女孩',
    speakerId: 'ICL_zh_female_huoponvhai_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'dongfanghaoran',
    name: '东方浩然',
    speakerId: 'zh_male_dongfanghaoran_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lvchaxiaoge',
    name: '绿茶小哥',
    speakerId: 'ICL_zh_male_lvchaxiaoge',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jiaoruoluo',
    name: '娇弱萝莉',
    speakerId: 'ICL_zh_female_jiaoruoluoli',
    gender: 'female',
    age: 'child',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lengdanshuli',
    name: '冷淡疏离',
    speakerId: 'ICL_zh_male_lengdanshuli_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'hanhoudunshi',
    name: '憨厚敦实',
    speakerId: 'ICL_zh_male_hanhoudunshi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'huopodiaoman',
    name: '活泼刁蛮',
    speakerId: 'ICL_zh_female_huopodiaoman_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'guzhibingjiao',
    name: '固执病娇',
    speakerId: 'ICL_zh_male_guzhibingjiao_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sajiaonianren',
    name: '撒娇粘人',
    speakerId: 'ICL_zh_male_sajiaonianren_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'guiyishenmi',
    name: '诡异神秘',
    speakerId: 'ICL_zh_male_guiyishenmi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruyacaijun',
    name: '儒雅才俊',
    speakerId: 'ICL_zh_male_ruyacaijun_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zhengzhiqingnian',
    name: '正直青年',
    speakerId: 'ICL_zh_male_zhengzhiqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jiaohannvwang',
    name: '娇憨女王',
    speakerId: 'ICL_zh_female_jiaohannvwang_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiaomengmei',
    name: '病娇萌妹',
    speakerId: 'ICL_zh_female_bingjiaomengmei_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingsenaigou',
    name: '青涩小生',
    speakerId: 'ICL_zh_male_qingsenaigou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chunzhenxuedi',
    name: '纯真学弟',
    speakerId: 'ICL_zh_male_chunzhenxuedi_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'youroubangzhu',
    name: '优柔帮主',
    speakerId: 'ICL_zh_male_youroubangzhu_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yourougongzi',
    name: '优柔公子',
    speakerId: 'ICL_zh_male_yourougongzi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tiaopigongzhu',
    name: '调皮公主',
    speakerId: 'ICL_zh_female_tiaopigongzhu_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tiexinnanyou',
    name: '贴心男友',
    speakerId: 'ICL_zh_male_tiexinnanyou_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shaonianjiangjun',
    name: '少年将军',
    speakerId: 'ICL_male_shaonianjiangjun_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiaogege',
    name: '病娇哥哥',
    speakerId: 'ICL_zh_male_bingjiaogege_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'roleplay',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xuebanantongzhuo',
    name: '学霸男同桌',
    speakerId: 'ICL_zh_male_xuebanantongzhuo_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'youmoshushu',
    name: '幽默叔叔',
    speakerId: 'ICL_zh_male_youmoshushu_tob',
    gender: 'male',
    age: 'senior',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jiaxiaozi',
    name: '假小子',
    speakerId: 'ICL_zh_female_jiaxiaozi_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenrounantongzhuo',
    name: '温柔男同桌',
    speakerId: 'ICL_zh_male_wenrounantongzhuo_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'youmodaye',
    name: '幽默大爷',
    speakerId: 'ICL_zh_male_youmodaye_tob',
    gender: 'male',
    age: 'senior',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'asmryexiu',
    name: '枕边低语',
    speakerId: 'zh_male_asmryexiu_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shenmifashi',
    name: '神秘法师',
    speakerId: 'zh_male_shenmifashi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jiaochuanmars',
    name: '娇喘女声',
    speakerId: 'zh_female_jiaochuan_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'livelybro',
    name: '开朗弟弟',
    speakerId: 'zh_male_livelybro_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'flatterynv',
    name: '谄媚女声',
    speakerId: 'zh_female_flattery_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lengjunshangsi',
    name: '冷峻上司',
    speakerId: 'ICL_zh_male_lengjunshangsi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xiaoge-v1',
    name: '寡言小哥',
    speakerId: 'ICL_zh_male_xiaoge_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'renyuwangzi-v1',
    name: '清朗温润',
    speakerId: 'ICL_zh_male_renyuwangzi_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xiaosha-v1',
    name: '潇洒随性',
    speakerId: 'ICL_zh_male_xiaosha_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'liyisheng-v1',
    name: '清冷矜贵',
    speakerId: 'ICL_zh_male_liyisheng_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xingjiwangzi-v1',
    name: '温柔内敛',
    speakerId: 'ICL_zh_male_xingjiwangzi_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sigeshiye-v1',
    name: '低沉缱绻',
    speakerId: 'ICL_zh_male_sigeshiye_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lanyingcaohunshi',
    name: '蓝银草魂师',
    speakerId: 'ICL_zh_male_lanyingcaohunshi_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'liumengdie-v1',
    name: '清冷高雅',
    speakerId: 'ICL_zh_female_liumengdie_v1_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tianmeiv1',
    name: '甜美娇俏',
    speakerId: 'ICL_zh_female_linxueying_v1_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'rouguhunshi',
    name: '柔骨魂师',
    speakerId: 'ICL_zh_female_rouguhunshi_v1_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chengshuv1',
    name: '成熟温柔',
    speakerId: 'ICL_zh_female_chengshu_v1_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bv139',
    name: '高冷沉稳',
    speakerId: 'zh_male_bv139_audiobook_ummv3_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'audiobook',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'fengfashaonian',
    name: '风发少年',
    speakerId: 'zh_male_fengfashaonian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'cixingnansang',
    name: '磁性男嗓',
    speakerId: 'zh_male_cixingnansang_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chengshuzongcai',
    name: '成熟总裁',
    speakerId: 'zh_male_chengshuzongcai_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aojiaojingying',
    name: '傲娇精英',
    speakerId: 'zh_male_aojiaojingying_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aojiaogongzi',
    name: '傲娇公子',
    speakerId: 'zh_male_aojiaogongzi_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'fuheigongzi',
    name: '腹黑公子',
    speakerId: 'ICL_zh_male_fuheigongzi_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'nuanxinxuejie',
    name: '暖心学姐',
    speakerId: 'ICL_zh_female_nuanxinxuejie_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'keainvsheng',
    name: '可爱女生',
    speakerId: 'ICL_zh_female_keainvsheng_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chengshujiejie',
    name: '成熟姐姐',
    speakerId: 'ICL_zh_female_chengshujiejie_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiaojiejie',
    name: '病娇姐姐',
    speakerId: 'ICL_zh_female_bingjiaojiejie_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wumeiyujie',
    name: '妩媚御姐',
    speakerId: 'ICL_zh_female_wumeiyujie_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aojiaonvyou',
    name: '傲娇女友',
    speakerId: 'ICL_zh_female_aojiaonvyou_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tiexinnyou',
    name: '贴心女友',
    speakerId: 'ICL_zh_female_tiexinnvyou_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xingganyujie',
    name: '性感御姐',
    speakerId: 'ICL_zh_female_xingganyujie_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiaodidi',
    name: '病娇弟弟',
    speakerId: 'ICL_zh_male_bingjiaodidi_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aomanshaoye',
    name: '傲慢少爷',
    speakerId: 'ICL_zh_male_aomanshaoye_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aiqilingren',
    name: '傲气凌人',
    speakerId: 'ICL_zh_male_aiqilingren_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bingjiaobailian',
    name: '病娇白莲',
    speakerId: 'ICL_zh_male_bingjiaobailian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lauren',
    name: 'Lauren',
    speakerId: 'en_female_lauren_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'campaign-jamal',
    name: 'Energetic Male II',
    speakerId: 'en_male_campaign_jamal_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'advertising',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'gotham-hero',
    name: 'Gotham Hero',
    speakerId: 'en_male_chris_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'flirty-darcie',
    name: 'Flirty Female',
    speakerId: 'en_female_product_darcie_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'advertising',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'peaceful-emotional',
    name: 'Peaceful Female',
    speakerId: 'en_female_emotional_moon_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'nara',
    name: 'Nara',
    speakerId: 'en_female_nara_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'bruce',
    name: 'Bruce',
    speakerId: 'en_male_bruce_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'michael',
    name: 'Michael',
    speakerId: 'en_male_michael_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sophie-en',
    name: 'Sophie',
    speakerId: 'zh_female_sophie_conversation_wvae_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'daisy-en',
    name: 'Daisy',
    speakerId: 'en_female_dacey_conversation_wvae_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'owen-en',
    name: 'Owen',
    speakerId: 'en_male_charlie_conversation_wvae_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'luna-en',
    name: 'Sarah',
    speakerId: 'en_female_sarah_new_conversation_wvae_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'michael-icl',
    name: 'Michael',
    speakerId: 'ICL_en_male_michael_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'charlie-icl',
    name: 'Charlie',
    speakerId: 'ICL_en_female_cc_cm_v1_tob',
    gender: 'female',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'big-boogie',
    name: 'Big Boogie',
    speakerId: 'ICL_en_male_oogie2_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'advertising',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'frosty-man',
    name: 'Frosty Man',
    speakerId: 'ICL_en_male_frosty1_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'grinch',
    name: 'The Grinch',
    speakerId: 'ICL_en_male_grinch2_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'zayne',
    name: 'Zayne',
    speakerId: 'ICL_en_male_zayne_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jigsaw',
    name: 'Jigsaw',
    speakerId: 'ICL_en_male_cc_jigsaw_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chucky',
    name: 'Chucky Man',
    speakerId: 'ICL_en_male_cc_penny_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'kevin-mccallister',
    name: 'Kevin McCallister',
    speakerId: 'ICL_en_male_kevin2_tob',
    gender: 'male',
    age: 'child',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xavier',
    name: 'Xavier',
    speakerId: 'ICL_en_male_xavier1_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'noah',
    name: 'Noah',
    speakerId: 'ICL_en_male_cc_dracula_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'adam-en',
    name: 'Adam',
    speakerId: 'en_male_adam_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'amanda-en',
    name: 'Amanda',
    speakerId: 'en_female_amanda_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jackson-en',
    name: 'Jackson',
    speakerId: 'en_male_jackson_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'delicate-girl',
    name: 'Delicate Girl',
    speakerId: 'en_female_daisy_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'dave-en',
    name: 'Dave',
    speakerId: 'en_male_dave_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'hades-en',
    name: 'Hades',
    speakerId: 'en_male_hades_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'onez-en',
    name: 'Onez',
    speakerId: 'en_female_onez_moon_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'emily-en',
    name: 'Emily',
    speakerId: 'en_female_emily_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'daniel-en',
    name: 'Daniel',
    speakerId: 'zh_male_xudong_conversation_wvae_bigtts',
    gender: 'male',
    age: 'young',
    language: 'en',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'alastor-en',
    name: 'Alastor',
    speakerId: 'ICL_en_male_cc_alastor_tob',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'smith-en',
    name: 'Smith',
    speakerId: 'en_male_smith_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'anna-en',
    name: 'Anna',
    speakerId: 'en_female_anna_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'aussie-ethan',
    name: 'Ethan',
    speakerId: 'ICL_en_male_aussie_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sarah-aussie',
    name: 'Sarah',
    speakerId: 'en_female_sarah_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'dryw-aussie',
    name: 'Dryw',
    speakerId: 'en_male_dryw_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'en',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'diana-sp',
    name: 'Diana',
    speakerId: 'multi_female_maomao_conversation_wvae_bigtts',
    gender: 'female',
    age: 'young',
    language: 'es',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lucia-sp',
    name: 'Lucía',
    speakerId: 'multi_male_M100_conversation_wvae_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'es',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'sofia-sp',
    name: 'Sofía',
    speakerId: 'multi_female_sophie_conversation_wvae_bigtts',
    gender: 'female',
    age: 'young',
    language: 'es',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'daniel-sp',
    name: 'Daníel',
    speakerId: 'multi_male_xudong_conversation_wvae_bigtts',
    gender: 'male',
    age: 'young',
    language: 'es',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'youyoujunzi-jp',
    name: 'ひかる（光）',
    speakerId: 'multi_zh_male_youyoujunzi_moon_bigtts',
    gender: 'male',
    age: 'young',
    language: 'jp',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'satomi-jp',
    name: 'さとみ（智美）',
    speakerId: 'multi_female_sophie_conversation_wvae_bigtts',
    gender: 'female',
    age: 'young',
    language: 'jp',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'masao-jp',
    name: 'まさお（正男）',
    speakerId: 'multi_male_xudong_conversation_wvae_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'jp',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tsuki-jp',
    name: 'つき（月）',
    speakerId: 'multi_female_maomao_conversation_wvae_bigtts',
    gender: 'female',
    age: 'young',
    language: 'jp',
    scene: 'conversation',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'akemi-jp',
    name: 'あけみ（朱美）',
    speakerId: 'multi_female_gaolengyujie_moon_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'jp',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'kazune-jp',
    name: 'かずね（和音）/Javier or Álvaro',
    speakerId: 'multi_male_jingqiangkanye_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'jp',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'haruko-jp',
    name: 'はるこ（晴子）/Esmeralda',
    speakerId: 'multi_female_shuangkuaisisi_moon_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'jp',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'hiroshi-wanqu',
    name: 'ひろし（広志）/Roberto',
    speakerId: 'multi_male_wanqudashu_moon_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'jp',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lixingyuanzi',
    name: '理性圆子',
    speakerId: 'ICL_zh_female_lixingyuanzi_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingtiantaotao',
    name: '清甜桃桃',
    speakerId: 'ICL_zh_female_qingtiantaotao_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingxixiaoxue',
    name: '清晰小雪',
    speakerId: 'ICL_zh_female_qingxixiaoxue_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingtianmeimei',
    name: '清甜莓莓',
    speakerId: 'ICL_zh_female_qingtianmeimei_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'kailangtingting',
    name: '开朗婷婷',
    speakerId: 'ICL_zh_female_kailangtingting_cs_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingxinmumu',
    name: '清新沐沐',
    speakerId: 'ICL_zh_male_qingxinmumu_cs_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'shuanglangxiaoyang',
    name: '爽朗小阳',
    speakerId: 'ICL_zh_male_shuanglangxiaoyang_cs_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingxinbobo',
    name: '清新波波',
    speakerId: 'ICL_zh_male_qingxinbobo_cs_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenwanshanshan',
    name: '温婉珊珊',
    speakerId: 'ICL_zh_female_wenwanshanshan_cs_tob',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tianmeixiaoyu',
    name: '甜美小雨',
    speakerId: 'ICL_zh_female_tianmeixiaoyu_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'chenwenmingzai',
    name: '沉稳明仔',
    speakerId: 'ICL_zh_male_chenwenmingzai_cs_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qinqiexiaozhuo',
    name: '亲切小卓',
    speakerId: 'ICL_zh_male_qinqiexiaozhuo_cs_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lingdongxinxin',
    name: '灵动欣欣',
    speakerId: 'ICL_zh_female_lingdongxinxin_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'guaiqiaokeer',
    name: '乖巧可儿',
    speakerId: 'ICL_zh_female_guaiqiaokeer_cs_tob',
    gender: 'female',
    age: 'child',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'nuanxinqianqian',
    name: '暖心茜茜',
    speakerId: 'ICL_zh_female_nuanxinqianqian_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'customerService',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruanmengtuanzi',
    name: '软萌团子',
    speakerId: 'ICL_zh_female_ruanmengtuanzi_cs_tob',
    gender: 'female',
    age: 'child',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yangguangyangyang',
    name: '阳光洋洋',
    speakerId: 'ICL_zh_male_yangguangyangyang_cs_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruanmengtangtang',
    name: '软萌糖糖',
    speakerId: 'ICL_zh_female_ruanmengtangtang_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xiuliqianqian',
    name: '秀丽倩倩',
    speakerId: 'ICL_zh_female_xiuliqianqian_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jingxuan-kaifang',
    name: '开心小鸿',
    speakerId: 'ICL_zh_female_kaixinxiaohong_cs_tob',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wuzetian',
    name: '武则天',
    speakerId: 'zh_female_wuzetian_mars_bigtts',
    gender: 'female',
    age: 'senior',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'gujie',
    name: '顾姐',
    speakerId: 'zh_female_gujie_mars_bigtts',
    gender: 'female',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'yingtaowanzi',
    name: '樱桃丸子',
    speakerId: 'zh_female_yingtaowanzi_mars_bigtts',
    gender: 'female',
    age: 'child',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'silang',
    name: '四郎',
    speakerId: 'zh_male_silang_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qiaopinsheng',
    name: '俏皮女声',
    speakerId: 'zh_female_qiaopinvsheng_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'lanxiaoyang',
    name: '懒音绵宝',
    speakerId: 'zh_male_lanxiaoyang_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'dongmanhaimian',
    name: '亮嗓萌仔',
    speakerId: 'zh_male_dongmanhaimian_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'cishengjieshuo',
    name: '磁性解说男声/Morgan',
    speakerId: 'zh_male_jieshuonansheng_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'jitangmeimei',
    name: '鸡汤妹妹/Hope',
    speakerId: 'zh_female_jitangmeimei_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'tiexinnvsheng',
    name: '贴心女声/Candy',
    speakerId: 'zh_female_tiexinnvsheng_mars_bigtts',
    gender: 'female',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xionger',
    name: '熊二',
    speakerId: 'zh_male_xionger_mars_bigtts',
    gender: 'male',
    age: 'child',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'peiqi',
    name: '佩奇猪',
    speakerId: 'zh_female_peiqi_mars_bigtts',
    gender: 'female',
    age: 'child',
    language: 'zh',
    scene: 'dubbing',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'neiqiancaishuo',
    name: '内敛才俊',
    speakerId: 'ICL_zh_male_neiliancaijun_e991be511569_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'audiobook',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'wenruoyangyang',
    name: '温暖少年',
    speakerId: 'ICL_zh_male_yangyang_v1_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruyafacaijun',
    name: '儒雅公子',
    speakerId: 'ICL_zh_male_flc_v1_tob',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'xuanjiangtianyi',
    name: '悬疑解说',
    speakerId: 'zh_male_changtianyi_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'storytelling',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'ruyaqingnian',
    name: '儒雅青年',
    speakerId: 'zh_male_ruyaqingnian_mars_bigtts',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'narration',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'baqiqingshu',
    name: '霸气青叔',
    speakerId: 'zh_male_baqiqingshu_mars_bigtts',
    gender: 'male',
    age: 'senior',
    language: 'zh',
    scene: 'narration',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'qingcang',
    name: '擎苍',
    speakerId: 'zh_male_qingcang_mars_bigtts',
    gender: 'male',
    age: 'middle',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
  {
    id: 'fanjuqingnian',
    name: '反卷青年',
    speakerId: 'ICL_zh_male_fanjuanqingnian_tob',
    gender: 'male',
    age: 'young',
    language: 'zh',
    scene: 'general',
    modelSupport: ['doubao-text-to-speech/seed-tts-1.0-concurr'],
  },
]

export const allVoices: VoiceInfo[] = [...tts2Voices, ...tts1Voices]

export interface CustomVoice {
  id: string
  name: string
  modelId: string
  speakerId: string
  sampleUrl: string
  createdAt: number
}

export default allVoices
